### ISSUE TITLE
Translation into Czech

### ISSUE THREAD

**Issue by amotl** [gafam/gafam-poster-translations#19]
Hi @trendspotter,

we see that 0fcfe77c04 aimed to bring in the translations into Czech. However, the patch seems to contain empty translation strings only.

It would be very sweet to bring in those translations, because it would raise the translation count to 28, making it a perfect opportunity to refresh the mosaic image [1], because we optimally need an even number of translations to cover the canvas 100% without leaving any gap.

The last time it was rendered, we had translations into 24 languages, so it's been a while already.

With kind regards,
Andreas.

[1] https://ptrace.gafam.info/unofficial/img/mosaic/lqdn-gafam-poster-mosaic-color-horizontal.png

**Comment by trendspotter** [comment]
Hello Andreas, 

Yes, I have requested the creation of a new workspace for Czech translation on weblate site, but I haven't started translating yet.  Probably happened that the weblate bot automatically created an update with PR of the translation file, even though no translation has been completed yet, 

I will continue later, then your wish will surely come true :)

**Comment by amotl** [comment]
Hi again,

the translations into Czech have been rendered, I am referencing the colored variants here [1,2,3]. Thank you again for your contribution.

With kind regards,
Andreas.

[1] https://ptrace.gafam.info/unofficial/pdf/color/lqdn-gafam-poster-cs-color.pdf
[2] https://ptrace.gafam.info/unofficial/img/color/lqdn-gafam-poster-cs-color-5x1-2560x.png
[3] https://ptrace.gafam.info/unofficial/svg/color/lqdn-gafam-poster-cs-color/

**Comment by trendspotter** [comment]
Thank you for the update. 

but... I discovered a few small errors in the render text. They are probably caused by a wrong character set of the font, which doesn't support Czech character set.  (?)   
Please use UTF-8 Unicode character sets and properly font, where the "**ý**" character will be interpreted exactly, not as an "**i**" character .
In my translation on weblate the text is correct. 

The text is readable with errors, but it has gross misspellings that could detract from the campaign message. 

Please find the cause of this error and correct it.

**Comment by amotl** [comment]
Hi again,

thanks for notifying us about the glyph issue. https://github.com/posterkit/posterkit-sandbox/commit/7f4d964f53 now uses Lato for rendering the Czech language, as suggested by @Informatic at https://github.com/posterkit/posterkit-sandbox/issues/1.

Please let us know if this works for you. We would also be interested to find another font which looks more heavy than LatoWebHeavy, preferably as heavy as the original FuturaMaxiBold. The problem in finding one is that it looks like some of those fonts lack support for non-latin glyphs, right?

With kind regards,
Andreas.

**Comment by trendspotter** [comment]
I explore similar issue with Lato and Roboto font here https://community.karrot.world/t/better-use-roboto-font/689
Maybe there is a solution. 

this is a very common problem when using freely available web fonts with insufficient Czech support. I don't know why. 

The posters seem to be fine now. Thanks!

**Comment by amotl** [comment]
> The posters seem to be fine now. Thanks!

Thank you!
